--- !ditz.rubyforge.org,2008-03-06/project 
name: pasten
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: pasten
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.9"
  status: :released
  release_time: 2013-12-22 01:26:56.462826 Z
  log_events: 
  - - 2013-12-20 08:34:46.006068 Z
    - Caoimhe Chaos <caoimhechaos@protonmail.com>
    - created
    - First feature-complete but terribly web-designed version.
  - - 2013-12-22 01:26:56.462836 Z
    - Caoimhe Chaos <caoimhechaos@protonmail.com>
    - released
    - With all issues resolved, we're ready for the first release.
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.10"
  status: :released
  release_time: 2014-01-07 14:47:42.193314 Z
  log_events: 
  - - 2014-01-07 13:51:22.681926 Z
    - Caoimhe Chaos <caoimhechaos@protonmail.com>
    - created
    - A slightly styled variant of the 0.9 release.
  - - 2014-01-07 14:47:42.193327 Z
    - Caoimhe Chaos <caoimhechaos@protonmail.com>
    - released
    - Release version 0.10 with the few changes it has.
